server:
  port: 8888
spring:
  application:
    name: EurekaServer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9999/eureka
  server:
    enable-self-preservation: false
    #eviction-interval-timer-in-ms: 100
