spring:
  application:
    name: UserWeb04
  thymeleaf:
    cache: false
server:
  port: 7004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:9999/eureka
USERPROVIDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
      # 是否对所有操作都进行重试
    OkToRetryOnAllOperations: true
      # 切换实例的重试次数
    MaxAutoRetriesNextServer: 1
      # 对当前实例的重试次数
    MaxAutoRetries: 1
logging:
  level:
    com:
      offcn: debug
